---
title: "Second week assignment"
output: html_document
bibliography      : "refs.bib"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Foundational Paper
[@hoffman1995role]

Hoffman and Subramaniam’s (1995) study aimed to examine the relationship between saccade and attention (i.e. whether attention precedes a saccade). They tracked subjects’ eye movements with an eye tracker during attentional tasks. Results showed that making a saccade to a location improves the identification of the information in the same location. Additionally, subjects were more likely to shift their gaze from the center point (fixation) to the cued location (peripheral), even though the probability of the target stimulus was equal to all four locations. This pattern results in better detection of the targeted stimulus when the attentional cue and the saccade direction matched. All results together support the claim that attention and saccade are dependent. Meaning, prior to the eye movement, an attentional shift occurs. This study contributes to the research in attention by solving a long time dispute over what process comes first. These findings open a window to more specific research in the field. Understanding attentional processes can help us explain other psychological phenomena since attention has a key role in many processes. It allows measuring attention in an explicit way, through more objective (it is more difficult for the average subject to fake it) and accurate marker- eye movements. Moreover, saccade as a marker for attention can be used to study other populations, such as atypical developing. The relationship described in this study gives us a glimpse into a new area of research, where physiological cues are guided by a psychological process, such as attention.


# Newer Paper
[@zwaigenbaum2005behavioral]

In a study, done by Zwaigenbaum et al. (2005), shifting attention was examined as an early marker for risk to be later diagnosed with Autism Spectrum Disorder (ASD). Early diagnosis, followed by early intervention, is crucial for improvement in symptoms of ASD. One task in this study examined disengagement of attention, from a central fixation stimulus to a peripheral one using an eye tracker. The central stimulus either stayed on or off. The “on” trials are equivalent to the dual-task in the foundation article since two processes compete. Latency to start eye movement was measured. Results showed that delayed disengagement in the high-risk-ASD group predicts social impairments. Additionally, high-risk infants who perform worse at 12 months of age than in 6 months of age, were more likely to meet the criteria for ASD. As discussed in the foundational article, saccade could use as a marker for attention. This point was demonstrated in this study, where “sticky attention” behavior was measured through eye movement, specifically the latency between the peripheral stimulus onset and the beginning of a gaze shift. The contribution of this recent study is to clarify abnormal attention patterns in high-risk population, what in turn, can help improve early diagnosis of ASD. Previous studies tried to find predictive behaviors by using various methods (e.g parental reports, home-videos analysis). However, this study provides a biopsychological marker of abnormal attention patterns. A marker that was found to have a predictive merit in early ASD diagnosis.




